name: Build workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions: write-all

jobs:
  build_folder:
    runs-on: ubuntu-latest
    env:
      LOCATION: ${{ github.workspace }}/build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: build-command
      run: |
        npx @virtual-labs/buildexp clean-build-exp
        echo "LOCATION=${{ github.workspace }}/build" >> $GITHUB_ENV
        find . -type d -name "__pycache__" -exec rm -r {} +
        find . -type d -name "venv" -exec rm -r {} +
        cd ../
        git -C ${{ github.workspace }} checkout --orphan gh-pages
        git -C ${{ github.workspace }} reset
        git -C ${{ github.workspace }} add build/* -f
        git mv build/* ./dev -f

        git -C ${{ github.workspace }} config user.name "vleadadmin"
        git -C ${{ github.workspace }} config user.email "admin@vlabs.ac.in"
        "https://virtual-labs.github.io/${{ github.repository }}/dev" > link.txt
        git add link.txt
        git commit -m "gh page link added"
        git push origin dev
        git -C ${{ github.workspace }} commit -m "https://virtual-labs.github.io/${{ github.repository }}/dev click on the link to test your code."
        
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ORG_OWNER_GITHUB_TOKEN }}
        force: true
        branch: gh-pages