name: Deploy Extension

on:
  release:
    types:
      - published
      - edited

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Bump version
        run: |
          npm version patch --no-git-tag-version
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add package.json package-lock.json
          git commit -m "Bump version to $(node -p "require('./package.json').version")"
          git push origin dev
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          baseImagesUrl: https://raw.githubusercontent.com/virtual-labs/tool-web-ext-vscode/dev
          baseContentUrl: https://raw.githubusercontent.com/virtual-labs/tool-web-ext-vscode/dev
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
